import type {
  Testimonial,
  PortfolioItem,
  BlogPostPreview,
  CategoryPreview,
  CoursePreview,
  Stat,
} from "./types";

// ─────────────────────────────── Chiffres clés ──────────────────────────────
export const stats: Stat[] = [
  { id: "s1", label: "Projets livrés", value: 48, suffix: "+" },
  { id: "s2", label: "Clients accompagnés", value: 35, suffix: "+" },
  { id: "s3", label: "Apprenants formés", value: 1200, suffix: "+" },
  { id: "s4", label: "Satisfaction client", value: 98, suffix: "%" },
];

// ─────────────────────────────── Témoignages ────────────────────────────────
export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Aïcha Koné",
    role: "Directrice",
    company: "Boutique Élégance Abidjan",
    content:
      "Digital Access a transformé notre présence en ligne. Le site est magnifique, rapide, et nous recevons désormais des commandes chaque jour. Un accompagnement humain et professionnel du début à la fin.",
    rating: 5,
    featured: true,
  },
  {
    id: "t2",
    name: "Dr. Mamadou Traoré",
    role: "Fondateur",
    company: "Clinique La Providence",
    content:
      "Un travail sérieux et un vrai sens du détail. Notre plateforme de prise de rendez-vous fonctionne parfaitement et nos patients l'adorent. Je recommande sans hésiter.",
    rating: 5,
    featured: true,
  },
  {
    id: "t3",
    name: "Fatou Bamba",
    role: "Responsable formation",
    company: "Institut Supérieur ISTC",
    content:
      "La plateforme e-learning développée par Digital Access a révolutionné nos formations à distance. Interface intuitive, certificats automatiques, suivi des apprenants : tout y est.",
    rating: 5,
    featured: true,
  },
  {
    id: "t4",
    name: "Jean-Baptiste Yao",
    role: "Gérant",
    company: "Yao Import-Export",
    content:
      "Réactivité exemplaire et résultats au rendez-vous. Notre site institutionnel inspire confiance à nos partenaires internationaux. Merci à toute l'équipe.",
    rating: 5,
    featured: false,
  },
  {
    id: "t5",
    name: "Sandrine Adjoua",
    role: "CEO",
    company: "AfroStyle Cosmetics",
    content:
      "De la maquette au lancement, chaque étape a été soignée. Le dégradé de leur identité se retrouve partout, notre marque est enfin cohérente en ligne.",
    rating: 5,
    featured: false,
  },
];

// ─────────────────────────────── Portfolio ──────────────────────────────────
export const portfolio: PortfolioItem[] = [
  {
    id: "p1",
    title: "Lycée Scientifique de Yamoussoukro — Site institutionnel",
    slug: "lycee-scientifique-yamoussoukro",
    description:
      "Le site institutionnel officiel du Lycée Scientifique de Yamoussoukro, établissement public d'excellence de Côte d'Ivoire fondé en 1975. La plateforme met en valeur l'héritage et l'identité de l'école, détaille les filières scientifiques et le processus d'admission, présente la vie sur le campus et l'actualité des élèves et des alumni, et intègre un portail d'accès dédié aux élèves, parents et enseignants.",
    client: "Lycée Scientifique de Yamoussoukro",
    type: "Site institutionnel",
    category: "Institutionnel",
    url: "https://lsy.ci",
    coverImage: "/LSY.png",
    images: [],
    technologies: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Vercel"],
    featured: true,
    year: 2025,
  },
  {
    id: "p2",
    title: "Access Academy — Plateforme e-learning numérique",
    slug: "access-academy",
    description:
      "Access Academy, la plateforme e-learning que nous avons conçue et développée en interne pour l'apprentissage des métiers du numérique. Pensée pour un usage mobile même en 3G, elle réunit des formations 100 % en ligne animées par des mentors ivoiriens : leçons vidéo, quiz interactifs à correction immédiate, certificats vérifiables par QR code, gamification (XP, streaks) et paiement Mobile Money (Orange, MTN, Wave) intégralement en FCFA.",
    client: "Digital Access",
    type: "Plateforme e-learning",
    category: "E-learning",
    url: "https://academy.digitalaccess.ci",
    coverImage: "/Access_Academy.png",
    images: [],
    technologies: ["Next.js", "React", "Tailwind CSS", "Prisma", "Auth.js"],
    featured: true,
    year: 2025,
  },
  {
    id: "p3",
    title: "KoraStay — Plateforme de réservation de séjours",
    slug: "korastay",
    description:
      "KoraStay, une plateforme de réservation en ligne dédiée aux résidences meublées vérifiées et aux séjours découverte en Côte d'Ivoire et en Afrique de l'Ouest. Elle propose un moteur de recherche multi-critères (destination, dates, voyageurs, type de logement), des fiches logement détaillées avec tarifs en FCFA, et un parcours de réservation complet avec paiement Mobile Money — pensée mobile-first, aussi bien pour les voyageurs que pour les propriétaires partenaires.",
    client: "KoraStay",
    type: "Plateforme de réservation",
    category: "Réservation & Services",
    url: "https://korastay.net",
    coverImage: "/Korastay.png",
    images: [],
    technologies: ["Next.js", "React", "Tailwind CSS", "Mobile Money"],
    featured: true,
    year: 2025,
  },
  {
    id: "p4",
    title: "YEHLI — Site d'ONG éducative",
    slug: "yehli-ong-educative",
    description:
      "Le site institutionnel de l'ONG éducative YEHLI, qui accompagne enfants, jeunes et éducateurs vers l'excellence éducative, scientifique et citoyenne. Autour d'une identité forte et d'un slogan inspirant, il structure les rubriques Nos actions, Formations et Ressources, met en avant l'impact de l'association et transforme la visibilité en engagement grâce à des parcours clairs : demande d'intervention, don, bénévolat et adhésion.",
    client: "ONG YEHLI",
    type: "Site associatif",
    category: "ONG & Associatif",
    url: "https://yehli.org",
    coverImage: "/Yehli.png",
    images: [],
    technologies: ["Next.js", "React", "Tailwind CSS", "TypeScript", "Vercel"],
    featured: true,
    year: 2025,
  },
  {
    id: "p5",
    title: "ENS Abidjan — Portail institutionnel & concours",
    slug: "ens-abidjan",
    description:
      "Le portail officiel de l'École Normale Supérieure d'Abidjan, pôle de référence pour la formation des enseignants en Côte d'Ivoire. Le site présente l'ensemble des formations (initiale, continue, Master MEEF), l'organisation de l'établissement et un fil d'actualités dynamique centré sur les sessions de concours, tout en servant de point d'entrée aux candidats pour les préinscriptions et la consultation des convocations.",
    client: "École Normale Supérieure d'Abidjan",
    type: "Site institutionnel",
    category: "Institutionnel",
    url: "https://ens-abidjan.ci",
    coverImage: "/ENS.png",
    images: [],
    technologies: ["WordPress", "Elementor", "PHP", "MySQL"],
    featured: true,
    year: 2024,
  },
  {
    id: "p6",
    title: "EduWeb Graduation — Plateforme e-learning Master MEEF",
    slug: "eduweb-master-meef",
    description:
      "EduWeb Graduation, la plateforme e-learning universitaire bâtie sur Moodle pour piloter les formations diplômantes et certifiantes du Master MEEF, de l'ENS d'Abidjan et de la formation continue. Un espace d'apprentissage 100 % en ligne, structuré par parcours et aligné sur les recommandations de l'UNESCO et l'ODD4, qui centralise cours, forums, calendrier pédagogique et ressources dans une interface responsive à l'identité d'EduWeb.",
    client: "EduWeb",
    type: "Plateforme e-learning",
    category: "E-learning",
    url: "https://graduation.eduweb.ci",
    coverImage: "/Master_meef.png",
    images: [],
    technologies: ["Moodle", "PHP", "MySQL", "Bootstrap"],
    featured: true,
    year: 2024,
  },
  {
    id: "p7",
    title: "Université Ephrata — Plateforme FOAD & e-learning",
    slug: "universite-ephrata",
    description:
      "Une plateforme de Formation Ouverte et À Distance (FOAD) complète pour l'Université Ephrata, bâtie sur Moodle et habillée d'un thème sur-mesure aux couleurs bordeaux et or de l'établissement. Elle met en ligne l'offre académique de la Licence au Master et centralise scolarité, ressources numériques et espace e-learning dans un portail unique, accessible sur ordinateur comme sur mobile.",
    client: "Université Ephrata",
    type: "Plateforme e-learning",
    category: "E-learning",
    url: "https://u-ephrata.ci",
    coverImage: "/ephrata.png",
    images: [],
    technologies: ["Moodle", "PHP", "MySQL", "Thème sur-mesure"],
    featured: false,
    year: 2024,
  },
  {
    id: "p8",
    title: "OIJD — Plateforme institutionnelle jeunesse diplomatique",
    slug: "oijd-jeunesse-diplomatique",
    description:
      "La plateforme institutionnelle de l'Organisation Internationale de la Jeunesse Diplomatique (OIJD), Section Côte d'Ivoire, qui fédère une jeunesse engagée autour de la diplomatie, de la coopération internationale et du leadership responsable. Le site présente la mission et les départements de l'organisation, donne vie à ses actualités et à ses appels à opportunités (volontariat, projets, formations), et intègre un espace membre privé pour animer la communauté.",
    client: "OIJD — Section Côte d'Ivoire",
    type: "Site institutionnel",
    category: "Institutionnel",
    url: "https://oijd.vercel.app",
    coverImage: "/oijd.png",
    images: [],
    technologies: ["Next.js", "React", "Tailwind CSS", "Vercel"],
    featured: false,
    year: 2025,
  },
];

// ─────────────────────────────── Blog ───────────────────────────────────────
export const blogPosts: BlogPostPreview[] = [
  {
    id: "b1",
    title: "Pourquoi votre entreprise a besoin d'un site web en 2026",
    slug: "pourquoi-site-web-2026",
    excerpt:
      "À l'ère du digital, une présence en ligne n'est plus un luxe mais une nécessité. Découvrez pourquoi un site professionnel change tout pour votre activité.",
    category: "Stratégie digitale",
    tags: ["site web", "visibilité", "business"],
    author: { name: "Équipe Digital Access", role: "Rédaction" },
    readMinutes: 5,
    publishedAt: "2026-06-15T09:00:00.000Z",
  },
  {
    id: "b2",
    title: "Mobile Money : intégrer Orange, MTN et Wave sur votre site",
    slug: "integrer-mobile-money",
    excerpt:
      "Le Mobile Money domine les paiements en Côte d'Ivoire. Guide pratique pour accepter les paiements en ligne via CinetPay et FedaPay.",
    category: "Technique",
    tags: ["paiement", "mobile money", "cinetpay"],
    author: { name: "Équipe Digital Access", role: "Rédaction" },
    readMinutes: 7,
    publishedAt: "2026-05-28T09:00:00.000Z",
  },
  {
    id: "b3",
    title: "5 erreurs qui font fuir vos visiteurs (et comment les éviter)",
    slug: "5-erreurs-site-web",
    excerpt:
      "Temps de chargement, design daté, navigation confuse… Passons en revue les erreurs les plus courantes qui coûtent des clients à votre site.",
    category: "UX/UI",
    tags: ["ux", "conversion", "design"],
    author: { name: "Équipe Digital Access", role: "Rédaction" },
    readMinutes: 6,
    publishedAt: "2026-05-10T09:00:00.000Z",
  },
  {
    id: "b4",
    title: "Se former au numérique en Côte d'Ivoire : par où commencer ?",
    slug: "se-former-numerique-ci",
    excerpt:
      "Le numérique offre d'immenses opportunités. Découvrez comment Access Academy vous accompagne vers les métiers du web, du design et du marketing.",
    category: "Formation",
    tags: ["formation", "academy", "carrière"],
    author: { name: "Équipe Digital Access", role: "Rédaction" },
    readMinutes: 4,
    publishedAt: "2026-04-22T09:00:00.000Z",
  },
];

// ─────────────────────────────── Academy — catégories ───────────────────────
export const categories: CategoryPreview[] = [
  { id: "c1", name: "Développement Web", slug: "developpement-web", icon: "code", color: "#2B5CC6", courseCount: 12 },
  { id: "c2", name: "Design & UX/UI", slug: "design-ux-ui", icon: "palette", color: "#7C3AED", courseCount: 8 },
  { id: "c3", name: "Marketing Digital", slug: "marketing-digital", icon: "megaphone", color: "#00BCD4", courseCount: 9 },
  { id: "c4", name: "Bureautique", slug: "bureautique", icon: "file-text", color: "#059669", courseCount: 6 },
  { id: "c5", name: "Entrepreneuriat", slug: "entrepreneuriat", icon: "rocket", color: "#F59E0B", courseCount: 5 },
  { id: "c6", name: "Data & IA", slug: "data-ia", icon: "brain", color: "#1E8FE1", courseCount: 4 },
];

// ─────────────────────────────── Academy — cours vedettes ───────────────────
export const featuredCourses: CoursePreview[] = [
  {
    id: "co1",
    title: "Créer un site web moderne avec Next.js",
    slug: "site-web-nextjs",
    subtitle: "De zéro à la mise en ligne, sans prérequis",
    price: 45000,
    isFree: false,
    level: "BEGINNER",
    rating: 4.9,
    ratingCount: 132,
    enrollmentCount: 540,
    durationMinutes: 720,
    category: "Développement Web",
    categorySlug: "developpement-web",
    instructor: { name: "Koffi N'Guessan" },
  },
  {
    id: "co2",
    title: "Design d'interfaces avec Figma",
    slug: "design-figma",
    subtitle: "Concevez des interfaces qui convertissent",
    price: 35000,
    isFree: false,
    level: "INTERMEDIATE",
    rating: 4.8,
    ratingCount: 98,
    enrollmentCount: 410,
    durationMinutes: 540,
    category: "Design & UX/UI",
    categorySlug: "design-ux-ui",
    instructor: { name: "Awa Diallo" },
  },
  {
    id: "co3",
    title: "Marketing sur les réseaux sociaux",
    slug: "marketing-reseaux-sociaux",
    subtitle: "Développez votre audience et vos ventes",
    price: 0,
    isFree: true,
    level: "BEGINNER",
    rating: 4.7,
    ratingCount: 210,
    enrollmentCount: 980,
    durationMinutes: 360,
    category: "Marketing Digital",
    categorySlug: "marketing-digital",
    instructor: { name: "Marc Apo" },
  },
  {
    id: "co4",
    title: "Excel avancé pour la gestion",
    slug: "excel-avance",
    subtitle: "Tableaux croisés, formules et automatisation",
    price: 25000,
    isFree: false,
    level: "ADVANCED",
    rating: 4.9,
    ratingCount: 76,
    enrollmentCount: 320,
    durationMinutes: 480,
    category: "Bureautique",
    categorySlug: "bureautique",
    instructor: { name: "Grace Kouassi" },
  },
];

export const mockData = {
  stats,
  testimonials,
  portfolio,
  blogPosts,
  categories,
  featuredCourses,
};
