/**
 * catalogue-seed-part2.ts
 * Seeds 92 programs and 46 career paths.
 * Depends on courses and schools already existing in the database
 * (created by catalogue-seed.ts which runs first).
 */

import { PrismaClient } from "../generated/client";

const prisma = new PrismaClient();

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface ProgramData {
  code: string;
  school: string;
  title: string;
  slug: string;
  courses: string[];
  volume: number;
  price: number;
  cert: string;
  priority: string;
}

interface CareerPathData {
  code: string;
  school: string;
  title: string;
  slug: string;
  targetJob: string;
  duration: string;
  programs: string[];
  finalProject: string;
  price: number;
  installments: string;
  cert: string;
  priority: string;
}

// ---------------------------------------------------------------------------
// 92 Programs
// ---------------------------------------------------------------------------

const PROGRAMS: ProgramData[] = [
  // ── PRG-CORE (S00) — 5 programs ──────────────────────────────────────
  {
    code: "PRG-CORE-01",
    school: "S00",
    title: "Socle de culture numérique et cyberhygiène",
    slug: "socle-de-culture-numerique-et-cyberhygiene",
    courses: ["CORE-001", "CORE-007", "CORE-008"],
    volume: 24,
    price: 40000,
    cert: "Micro-certification Culture numérique responsable",
    priority: "Vague 1",
  },
  {
    code: "PRG-CORE-02",
    school: "S00",
    title: "Communication et collaboration professionnelles",
    slug: "communication-et-collaboration-professionnelles",
    courses: ["CORE-002", "CORE-004", "CORE-012"],
    volume: 24,
    price: 40000,
    cert: "Micro-certification Collaboration professionnelle",
    priority: "Vague 1",
  },
  {
    code: "PRG-CORE-03",
    school: "S00",
    title: "Organisation, résolution de problèmes et gestion de projet",
    slug: "organisation-resolution-de-problemes-et-gestion-de-projet",
    courses: ["CORE-003", "CORE-005", "CORE-006"],
    volume: 26,
    price: 40000,
    cert: "Micro-certification Méthodes professionnelles",
    priority: "Vague 1",
  },
  {
    code: "PRG-CORE-04",
    school: "S00",
    title: "Portfolio, employabilité et insertion",
    slug: "portfolio-employabilite-et-insertion",
    courses: ["CORE-009", "CORE-010", "CORE-012"],
    volume: 26,
    price: 40000,
    cert: "Micro-certification Employabilité et portfolio",
    priority: "Vague 1",
  },
  {
    code: "PRG-CORE-05",
    school: "S00",
    title: "Fondamentaux du freelance",
    slug: "fondamentaux-du-freelance",
    courses: ["CORE-011", "ENT-005", "ENT-009", "ENT-016"],
    volume: 58,
    price: 75000,
    cert: "Micro-certification Premiers pas en freelance",
    priority: "Vague 2",
  },

  // ── PRG-AI (S01) — 9 programs ────────────────────────────────────────
  {
    code: "PRG-AI-01",
    school: "S01",
    title: "Culture et usage responsable de l'IA",
    slug: "culture-et-usage-responsable-de-lia",
    courses: ["AI-001", "AI-004", "AI-014", "CORE-007"],
    volume: 38,
    price: 55000,
    cert: "Micro-certification Culture IA responsable",
    priority: "Vague 1",
  },
  {
    code: "PRG-AI-02",
    school: "S01",
    title: "Prompt Engineering professionnel",
    slug: "prompt-engineering-professionnel",
    courses: ["AI-002", "AI-003", "AI-004"],
    volume: 34,
    price: 40000,
    cert: "Micro-certification Prompt Engineering professionnel",
    priority: "Vague 1",
  },
  {
    code: "PRG-AI-03",
    school: "S01",
    title: "Productivité professionnelle avec l'IA",
    slug: "productivite-professionnelle-avec-lia",
    courses: ["AI-005", "AI-006", "AI-007", "CORE-002"],
    volume: 48,
    price: 55000,
    cert: "Micro-certification Productivité augmentée par l'IA",
    priority: "Vague 1",
  },
  {
    code: "PRG-AI-04",
    school: "S01",
    title: "Création d'assistants IA métier",
    slug: "creation-dassistants-ia-metier",
    courses: ["AI-008", "AI-009", "AI-014"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Assistant IA métier",
    priority: "Vague 1",
  },
  {
    code: "PRG-AI-05",
    school: "S01",
    title: "Automatisation avec Make",
    slug: "automatisation-avec-make",
    courses: ["AI-010", "CORE-005"],
    volume: 30,
    price: 40000,
    cert: "Micro-certification Automatisation Make",
    priority: "Vague 1",
  },
  {
    code: "PRG-AI-06",
    school: "S01",
    title: "Automatisation avec n8n",
    slug: "automatisation-avec-n8n",
    courses: ["AI-011", "CORE-005"],
    volume: 32,
    price: 40000,
    cert: "Micro-certification Automatisation n8n",
    priority: "Vague 1",
  },
  {
    code: "PRG-AI-07",
    school: "S01",
    title: "Conception d'agents IA junior",
    slug: "conception-dagents-ia-junior",
    courses: ["AI-012", "AI-013", "AI-009", "AI-014"],
    volume: 66,
    price: 75000,
    cert: "Micro-certification Agents IA junior",
    priority: "Vague 2",
  },
  {
    code: "PRG-AI-08",
    school: "S01",
    title: "Gouvernance et adoption de l'IA",
    slug: "gouvernance-et-adoption-de-lia",
    courses: ["AI-014", "AI-015", "CORE-006"],
    volume: 40,
    price: 55000,
    cert: "Micro-certification Gouvernance et adoption IA",
    priority: "Vague 1",
  },
  {
    code: "PRG-AI-09",
    school: "S01",
    title: "Création de contenu avec l'IA",
    slug: "creation-de-contenu-avec-lia",
    courses: ["AI-007", "DES-018", "MKT-023"],
    volume: 42,
    price: 55000,
    cert: "Micro-certification Création de contenu assistée par IA",
    priority: "Vague 2",
  },

  // ── PRG-DEV (S02) — 12 programs ──────────────────────────────────────
  {
    code: "PRG-DEV-01",
    school: "S02",
    title: "Fondamentaux du Web",
    slug: "fondamentaux-du-web",
    courses: ["DEV-001", "DEV-002", "DEV-003", "DEV-004"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Intégration Web",
    priority: "Vague 1",
  },
  {
    code: "PRG-DEV-02",
    school: "S02",
    title: "JavaScript et TypeScript",
    slug: "javascript-et-typescript",
    courses: ["DEV-005", "DEV-006", "DEV-007"],
    volume: 60,
    price: 75000,
    cert: "Micro-certification JavaScript & TypeScript",
    priority: "Vague 1",
  },
  {
    code: "PRG-DEV-03",
    school: "S02",
    title: "Git, collaboration et qualité",
    slug: "git-collaboration-et-qualite",
    courses: ["DEV-008", "DEV-016", "DEV-022"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Collaboration et qualité logicielle",
    priority: "Vague 1",
  },
  {
    code: "PRG-DEV-04",
    school: "S02",
    title: "Développement Front-End avec React",
    slug: "developpement-front-end-avec-react",
    courses: ["DEV-009", "DEV-023"],
    volume: 40,
    price: 55000,
    cert: "Micro-certification React Front-End",
    priority: "Vague 1",
  },
  {
    code: "PRG-DEV-05",
    school: "S02",
    title: "Applications Web avec Next.js",
    slug: "applications-web-avec-next-js",
    courses: ["DEV-010", "DEV-015", "DEV-017"],
    volume: 60,
    price: 75000,
    cert: "Micro-certification Next.js",
    priority: "Vague 1",
  },
  {
    code: "PRG-DEV-06",
    school: "S02",
    title: "Développement Back-End et API",
    slug: "developpement-back-end-et-api",
    courses: ["DEV-011", "DEV-015", "DEV-016"],
    volume: 62,
    price: 75000,
    cert: "Micro-certification API sécurisée",
    priority: "Vague 1",
  },
  {
    code: "PRG-DEV-07",
    school: "S02",
    title: "Bases de données applicatives",
    slug: "bases-de-donnees-applicatives",
    courses: ["DEV-013", "DEV-014"],
    volume: 38,
    price: 55000,
    cert: "Micro-certification Données pour développeurs",
    priority: "Vague 1",
  },
  {
    code: "PRG-DEV-08",
    school: "S02",
    title: "PHP et Laravel",
    slug: "php-et-laravel",
    courses: ["DEV-012", "DEV-013", "DEV-015"],
    volume: 60,
    price: 75000,
    cert: "Micro-certification Laravel",
    priority: "Vague 2",
  },
  {
    code: "PRG-DEV-09",
    school: "S02",
    title: "Déploiement, Docker et Cloud",
    slug: "deploiement-docker-et-cloud",
    courses: ["DEV-017", "DEV-018", "CYB-017"],
    volume: 48,
    price: 55000,
    cert: "Micro-certification Déploiement Cloud junior",
    priority: "Vague 2",
  },
  {
    code: "PRG-DEV-10",
    school: "S02",
    title: "WordPress professionnel",
    slug: "wordpress-professionnel-prg",
    courses: ["DEV-019", "CYB-011", "DEV-023"],
    volume: 52,
    price: 75000,
    cert: "Micro-certification WordPress professionnel",
    priority: "Vague 1",
  },
  {
    code: "PRG-DEV-11",
    school: "S02",
    title: "Applications No-Code avec FlutterFlow",
    slug: "applications-no-code-avec-flutterflow",
    courses: ["DEV-020", "DEV-013", "CORE-005"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Conception No-Code",
    priority: "Vague 2",
  },
  {
    code: "PRG-DEV-12",
    school: "S02",
    title: "Développement mobile multiplateforme",
    slug: "developpement-mobile-multiplateforme-prg",
    courses: ["DEV-021", "DEV-011", "DEV-015"],
    volume: 72,
    price: 95000,
    cert: "Micro-certification Développement mobile junior",
    priority: "Vague 2",
  },

  // ── PRG-DATA (S03) — 10 programs ─────────────────────────────────────
  {
    code: "PRG-DATA-01",
    school: "S03",
    title: "Culture, qualité et gouvernance des données",
    slug: "culture-qualite-et-gouvernance-des-donnees",
    courses: ["DATA-001", "DATA-007", "DATA-018"],
    volume: 40,
    price: 55000,
    cert: "Micro-certification Gestion responsable des données",
    priority: "Vague 1",
  },
  {
    code: "PRG-DATA-02",
    school: "S03",
    title: "Excel professionnel",
    slug: "excel-professionnel",
    courses: ["DATA-002", "DATA-003", "DATA-004"],
    volume: 48,
    price: 55000,
    cert: "Micro-certification Excel professionnel",
    priority: "Vague 1",
  },
  {
    code: "PRG-DATA-03",
    school: "S03",
    title: "Analyse et tableaux de bord Excel",
    slug: "analyse-et-tableaux-de-bord-excel",
    courses: ["DATA-005", "DATA-006", "DATA-019"],
    volume: 46,
    price: 55000,
    cert: "Micro-certification Dashboard Excel",
    priority: "Vague 1",
  },
  {
    code: "PRG-DATA-04",
    school: "S03",
    title: "SQL pour les données",
    slug: "sql-pour-les-donnees",
    courses: ["DATA-008", "DATA-009", "DATA-010"],
    volume: 54,
    price: 75000,
    cert: "Micro-certification SQL et modélisation",
    priority: "Vague 1",
  },
  {
    code: "PRG-DATA-05",
    school: "S03",
    title: "Administration PostgreSQL junior",
    slug: "administration-postgresql-junior-prg",
    courses: ["DATA-010", "DATA-011", "CYB-010"],
    volume: 52,
    price: 75000,
    cert: "Micro-certification Administration PostgreSQL",
    priority: "Vague 2",
  },
  {
    code: "PRG-DATA-06",
    school: "S03",
    title: "Power BI : préparation et visualisation",
    slug: "power-bi-preparation-et-visualisation",
    courses: ["DATA-012", "DATA-013", "DATA-017"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Power BI fondamental",
    priority: "Vague 1",
  },
  {
    code: "PRG-DATA-07",
    school: "S03",
    title: "Power BI avancé et DAX",
    slug: "power-bi-avance-et-dax",
    courses: ["DATA-014", "DATA-015", "DATA-019"],
    volume: 56,
    price: 75000,
    cert: "Micro-certification Power BI avancé",
    priority: "Vague 1",
  },
  {
    code: "PRG-DATA-08",
    school: "S03",
    title: "Python pour l'analyse de données",
    slug: "python-pour-lanalyse-de-donnees-prg",
    courses: ["DATA-016", "DATA-017", "DATA-020"],
    volume: 56,
    price: 75000,
    cert: "Micro-certification Python Data",
    priority: "Vague 2",
  },
  {
    code: "PRG-DATA-09",
    school: "S03",
    title: "Reporting et intelligence décisionnelle",
    slug: "reporting-et-intelligence-decisionnelle",
    courses: ["DATA-015", "DATA-017", "DATA-019", "DATA-018"],
    volume: 66,
    price: 75000,
    cert: "Micro-certification Business Intelligence",
    priority: "Vague 1",
  },
  {
    code: "PRG-DATA-10",
    school: "S03",
    title: "Analyse de données assistée par IA",
    slug: "analyse-de-donnees-assistee-par-ia-prg",
    courses: ["DATA-020", "AI-004", "AI-006"],
    volume: 36,
    price: 55000,
    cert: "Micro-certification IA pour l'analyse",
    priority: "Vague 1",
  },

  // ── PRG-CYB (S04) — 9 programs ───────────────────────────────────────
  {
    code: "PRG-CYB-01",
    school: "S04",
    title: "Support et maintenance informatique",
    slug: "support-et-maintenance-informatique",
    courses: ["CYB-001", "CYB-002", "CYB-003"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Support informatique",
    priority: "Vague 1",
  },
  {
    code: "PRG-CYB-02",
    school: "S04",
    title: "Réseaux et systèmes fondamentaux",
    slug: "reseaux-et-systemes-fondamentaux",
    courses: ["CYB-004", "CYB-005", "CYB-006"],
    volume: 64,
    price: 75000,
    cert: "Micro-certification Systèmes et réseaux",
    priority: "Vague 1",
  },
  {
    code: "PRG-CYB-03",
    school: "S04",
    title: "Fondamentaux de la cybersécurité",
    slug: "fondamentaux-de-la-cybersecurite-prg",
    courses: ["CYB-007", "CYB-008", "CYB-009", "CORE-008"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Cyberhygiène professionnelle",
    priority: "Vague 1",
  },
  {
    code: "PRG-CYB-04",
    school: "S04",
    title: "Sauvegarde et continuité numérique",
    slug: "sauvegarde-et-continuite-numerique",
    courses: ["CYB-010", "CYB-016"],
    volume: 30,
    price: 40000,
    cert: "Micro-certification Continuité numérique PME",
    priority: "Vague 1",
  },
  {
    code: "PRG-CYB-05",
    school: "S04",
    title: "Sécurité WordPress",
    slug: "securite-wordpress-prg",
    courses: ["CYB-011", "CYB-013", "CYB-010"],
    volume: 52,
    price: 75000,
    cert: "Micro-certification Sécurité WordPress",
    priority: "Vague 1",
  },
  {
    code: "PRG-CYB-06",
    school: "S04",
    title: "Sécurité des applications Web",
    slug: "securite-des-applications-web-prg",
    courses: ["CYB-012", "CYB-013", "DEV-015"],
    volume: 64,
    price: 75000,
    cert: "Micro-certification Sécurité Web junior",
    priority: "Vague 2",
  },
  {
    code: "PRG-CYB-07",
    school: "S04",
    title: "Analyse SOC et journaux",
    slug: "analyse-soc-et-journaux",
    courses: ["CYB-014", "CYB-015", "CYB-013"],
    volume: 66,
    price: 75000,
    cert: "Micro-certification Analyste SOC junior",
    priority: "Vague 2",
  },
  {
    code: "PRG-CYB-08",
    school: "S04",
    title: "Sécurité numérique pour PME",
    slug: "securite-numerique-pour-pme",
    courses: ["CYB-016", "CYB-010", "CYB-008", "CYB-009"],
    volume: 52,
    price: 75000,
    cert: "Micro-certification Référent sécurité PME",
    priority: "Vague 1",
  },
  {
    code: "PRG-CYB-09",
    school: "S04",
    title: "Sécurité Cloud et IA",
    slug: "securite-cloud-et-ia",
    courses: ["CYB-017", "CYB-018", "AI-014"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Sécurité Cloud et IA",
    priority: "Vague 2",
  },

  // ── PRG-MKT (S05) — 11 programs ──────────────────────────────────────
  {
    code: "PRG-MKT-01",
    school: "S05",
    title: "Fondamentaux de la stratégie marketing",
    slug: "fondamentaux-de-la-strategie-marketing",
    courses: ["MKT-001", "MKT-002", "MKT-023"],
    volume: 34,
    price: 40000,
    cert: "Micro-certification Stratégie marketing digitale",
    priority: "Vague 1",
  },
  {
    code: "PRG-MKT-02",
    school: "S05",
    title: "Community Management opérationnel",
    slug: "community-management-operationnel",
    courses: ["MKT-003", "MKT-004", "MKT-008", "MKT-009"],
    volume: 54,
    price: 75000,
    cert: "Micro-certification Community Management",
    priority: "Vague 1",
  },
  {
    code: "PRG-MKT-03",
    school: "S05",
    title: "Création de contenu digital",
    slug: "creation-de-contenu-digital",
    courses: ["MKT-005", "MKT-006", "MKT-007", "DES-015"],
    volume: 64,
    price: 75000,
    cert: "Micro-certification Création de contenu digital",
    priority: "Vague 1",
  },
  {
    code: "PRG-MKT-04",
    school: "S05",
    title: "Publicité Meta Ads",
    slug: "publicite-meta-ads-prg",
    courses: ["MKT-010", "MKT-002", "MKT-009"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Meta Ads",
    priority: "Vague 1",
  },
  {
    code: "PRG-MKT-05",
    school: "S05",
    title: "Publicité Google Ads",
    slug: "publicite-google-ads-prg",
    courses: ["MKT-011", "MKT-002", "MKT-009"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Google Ads",
    priority: "Vague 2",
  },
  {
    code: "PRG-MKT-06",
    school: "S05",
    title: "Référencement naturel SEO",
    slug: "referencement-naturel-seo",
    courses: ["MKT-012", "MKT-013", "DEV-023"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification SEO junior",
    priority: "Vague 1",
  },
  {
    code: "PRG-MKT-07",
    school: "S05",
    title: "Email marketing et automatisation",
    slug: "email-marketing-et-automatisation",
    courses: ["MKT-014", "MKT-015", "MKT-016"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Email & Marketing Automation",
    priority: "Vague 1",
  },
  {
    code: "PRG-MKT-08",
    school: "S05",
    title: "Prospection, CRM et vente digitale",
    slug: "prospection-crm-et-vente-digitale",
    courses: ["MKT-016", "MKT-017", "MKT-018", "MKT-022"],
    volume: 56,
    price: 75000,
    cert: "Micro-certification Vente digitale et CRM",
    priority: "Vague 1",
  },
  {
    code: "PRG-MKT-09",
    school: "S05",
    title: "E-commerce avec Shopify",
    slug: "e-commerce-avec-shopify",
    courses: ["MKT-019", "MKT-021", "MKT-022"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Shopify et opérations e-commerce",
    priority: "Vague 1",
  },
  {
    code: "PRG-MKT-10",
    school: "S05",
    title: "E-commerce avec WooCommerce",
    slug: "e-commerce-avec-woocommerce",
    courses: ["MKT-020", "MKT-021", "MKT-022"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification WooCommerce et opérations e-commerce",
    priority: "Vague 2",
  },
  {
    code: "PRG-MKT-11",
    school: "S05",
    title: "Intelligence artificielle pour le marketing",
    slug: "intelligence-artificielle-pour-le-marketing-prg",
    courses: ["MKT-023", "AI-003", "AI-007"],
    volume: 42,
    price: 55000,
    cert: "Micro-certification IA Marketing",
    priority: "Vague 1",
  },

  // ── PRG-DES (S06) — 9 programs ───────────────────────────────────────
  {
    code: "PRG-DES-01",
    school: "S06",
    title: "Fondamentaux du design visuel",
    slug: "fondamentaux-du-design-visuel",
    courses: ["DES-001", "DES-002"],
    volume: 24,
    price: 40000,
    cert: "Micro-certification Fondamentaux du design",
    priority: "Vague 1",
  },
  {
    code: "PRG-DES-02",
    school: "S06",
    title: "Canva professionnel",
    slug: "canva-professionnel-prg",
    courses: ["DES-003", "DES-015", "DES-016"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Canva professionnel",
    priority: "Vague 1",
  },
  {
    code: "PRG-DES-03",
    school: "S06",
    title: "Création graphique avec Adobe",
    slug: "creation-graphique-avec-adobe",
    courses: ["DES-004", "DES-005"],
    volume: 48,
    price: 55000,
    cert: "Micro-certification Adobe graphique",
    priority: "Vague 2",
  },
  {
    code: "PRG-DES-04",
    school: "S06",
    title: "Identité visuelle et marque",
    slug: "identite-visuelle-et-marque",
    courses: ["DES-006", "DES-001", "DES-002"],
    volume: 46,
    price: 55000,
    cert: "Micro-certification Identité visuelle",
    priority: "Vague 1",
  },
  {
    code: "PRG-DES-05",
    school: "S06",
    title: "UX/UI Design avec Figma",
    slug: "ux-ui-design-avec-figma",
    courses: ["DES-007", "DES-008", "DES-009", "DES-010"],
    volume: 76,
    price: 95000,
    cert: "Micro-certification UX/UI Design",
    priority: "Vague 1",
  },
  {
    code: "PRG-DES-06",
    school: "S06",
    title: "Création photo et vidéo mobile",
    slug: "creation-photo-et-video-mobile",
    courses: ["DES-011", "DES-012"],
    volume: 32,
    price: 40000,
    cert: "Micro-certification Création mobile",
    priority: "Vague 1",
  },
  {
    code: "PRG-DES-07",
    school: "S06",
    title: "Montage vidéo professionnel",
    slug: "montage-video-professionnel",
    courses: ["DES-012", "DES-013"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Montage vidéo",
    priority: "Vague 1",
  },
  {
    code: "PRG-DES-08",
    school: "S06",
    title: "Motion Design junior",
    slug: "motion-design-junior",
    courses: ["DES-014", "DES-013"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Motion Design",
    priority: "Vague 2",
  },
  {
    code: "PRG-DES-09",
    school: "S06",
    title: "Portfolio créatif et IA visuelle",
    slug: "portfolio-creatif-et-ia-visuelle",
    courses: ["DES-017", "DES-018", "CORE-012"],
    volume: 32,
    price: 40000,
    cert: "Micro-certification Portfolio créatif augmenté",
    priority: "Vague 1",
  },

  // ── PRG-PROD (S07) — 9 programs ──────────────────────────────────────
  {
    code: "PRG-PROD-01",
    school: "S07",
    title: "Initiation numérique et bureautique",
    slug: "initiation-numerique-et-bureautique",
    courses: ["PROD-001", "PROD-002", "PROD-003", "PROD-004"],
    volume: 62,
    price: 75000,
    cert: "Micro-certification Bureautique fondamentale",
    priority: "Vague 1",
  },
  {
    code: "PRG-PROD-02",
    school: "S07",
    title: "Microsoft 365 professionnel",
    slug: "microsoft-365-professionnel",
    courses: ["PROD-002", "PROD-003", "PROD-004", "PROD-005"],
    volume: 68,
    price: 75000,
    cert: "Micro-certification Microsoft 365",
    priority: "Vague 1",
  },
  {
    code: "PRG-PROD-03",
    school: "S07",
    title: "Google Workspace professionnel",
    slug: "google-workspace-professionnel-prg",
    courses: ["PROD-006", "PROD-007", "PROD-009", "PROD-011"],
    volume: 62,
    price: 75000,
    cert: "Micro-certification Google Workspace",
    priority: "Vague 1",
  },
  {
    code: "PRG-PROD-04",
    school: "S07",
    title: "Gestion documentaire numérique",
    slug: "gestion-documentaire-numerique",
    courses: ["PROD-007", "PROD-015", "PROD-016"],
    volume: 48,
    price: 55000,
    cert: "Micro-certification Gestion documentaire",
    priority: "Vague 1",
  },
  {
    code: "PRG-PROD-05",
    school: "S07",
    title: "Administration, réunions et communication",
    slug: "administration-reunions-et-communication",
    courses: ["PROD-008", "PROD-009", "PROD-016"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Administration professionnelle",
    priority: "Vague 1",
  },
  {
    code: "PRG-PROD-06",
    school: "S07",
    title: "Reporting administratif",
    slug: "reporting-administratif-prg",
    courses: ["PROD-003", "PROD-010", "DATA-019"],
    volume: 48,
    price: 55000,
    cert: "Micro-certification Reporting administratif",
    priority: "Vague 1",
  },
  {
    code: "PRG-PROD-07",
    school: "S07",
    title: "Formulaires et collecte de données",
    slug: "formulaires-et-collecte-de-donnees",
    courses: ["PROD-011", "DATA-007", "PROD-006"],
    volume: 48,
    price: 55000,
    cert: "Micro-certification Collecte numérique",
    priority: "Vague 1",
  },
  {
    code: "PRG-PROD-08",
    school: "S07",
    title: "Organisation et assistance à distance",
    slug: "organisation-et-assistance-a-distance",
    courses: ["PROD-012", "PROD-013", "CORE-003"],
    volume: 38,
    price: 55000,
    cert: "Micro-certification Assistance virtuelle",
    priority: "Vague 1",
  },
  {
    code: "PRG-PROD-09",
    school: "S07",
    title: "Productivité et automatisation bureautique",
    slug: "productivite-et-automatisation-bureautique",
    courses: ["PROD-014", "AI-005", "AI-010"],
    volume: 46,
    price: 55000,
    cert: "Micro-certification Productivité numérique augmentée",
    priority: "Vague 1",
  },

  // ── PRG-ENT (S08) — 9 programs ───────────────────────────────────────
  {
    code: "PRG-ENT-01",
    school: "S08",
    title: "Fondamentaux de l'entrepreneuriat",
    slug: "fondamentaux-de-lentrepreneuriat",
    courses: ["ENT-001", "ENT-002", "ENT-003"],
    volume: 36,
    price: 55000,
    cert: "Micro-certification Fondamentaux entrepreneuriaux",
    priority: "Vague 1",
  },
  {
    code: "PRG-ENT-02",
    school: "S08",
    title: "Étude de marché et validation",
    slug: "etude-de-marche-et-validation",
    courses: ["ENT-002", "ENT-004", "MKT-002"],
    volume: 38,
    price: 55000,
    cert: "Micro-certification Validation de marché",
    priority: "Vague 1",
  },
  {
    code: "PRG-ENT-03",
    school: "S08",
    title: "Offre, prix et marque personnelle",
    slug: "offre-prix-et-marque-personnelle",
    courses: ["ENT-005", "ENT-006", "ENT-018"],
    volume: 40,
    price: 55000,
    cert: "Micro-certification Positionnement professionnel",
    priority: "Vague 1",
  },
  {
    code: "PRG-ENT-04",
    school: "S08",
    title: "Prospection, vente et négociation",
    slug: "prospection-vente-et-negociation",
    courses: ["ENT-007", "ENT-008", "MKT-018"],
    volume: 46,
    price: 55000,
    cert: "Micro-certification Vente de services",
    priority: "Vague 1",
  },
  {
    code: "PRG-ENT-05",
    school: "S08",
    title: "Proposition commerciale et gestion client",
    slug: "proposition-commerciale-et-gestion-client",
    courses: ["ENT-009", "ENT-016", "CORE-002"],
    volume: 42,
    price: 55000,
    cert: "Micro-certification Gestion de mission client",
    priority: "Vague 1",
  },
  {
    code: "PRG-ENT-06",
    school: "S08",
    title: "Gestion financière et pilotage d'activité",
    slug: "gestion-financiere-et-pilotage-dactivite",
    courses: ["ENT-010", "DATA-019"],
    volume: 30,
    price: 40000,
    cert: "Micro-certification Pilotage financier simplifié",
    priority: "Vague 1",
  },
  {
    code: "PRG-ENT-07",
    school: "S08",
    title: "Gestion de projet Agile",
    slug: "gestion-de-projet-agile",
    courses: ["ENT-011", "ENT-012", "CORE-005"],
    volume: 46,
    price: 55000,
    cert: "Micro-certification Gestion de projet Agile",
    priority: "Vague 1",
  },
  {
    code: "PRG-ENT-08",
    school: "S08",
    title: "Gestion de produit et lancement",
    slug: "gestion-de-produit-et-lancement",
    courses: ["ENT-013", "ENT-017", "ENT-018"],
    volume: 50,
    price: 55000,
    cert: "Micro-certification Lancement de produit numérique",
    priority: "Vague 2",
  },
  {
    code: "PRG-ENT-09",
    school: "S08",
    title: "Transformation numérique des PME",
    slug: "transformation-numerique-des-pme",
    courses: ["ENT-014", "ENT-015", "AI-015", "DATA-019"],
    volume: 70,
    price: 75000,
    cert: "Micro-certification Transformation numérique PME",
    priority: "Vague 1",
  },

  // ── PRG-EDU (S09) — 9 programs ───────────────────────────────────────
  {
    code: "PRG-EDU-01",
    school: "S09",
    title: "Fondamentaux de la pédagogie numérique",
    slug: "fondamentaux-de-la-pedagogie-numerique",
    courses: ["EDU-001", "EDU-002", "EDU-003"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Pédagogie numérique",
    priority: "Vague 1",
  },
  {
    code: "PRG-EDU-02",
    school: "S09",
    title: "Scénarisation et production de cours",
    slug: "scenarisation-et-production-de-cours",
    courses: ["EDU-004", "EDU-010", "EDU-013"],
    volume: 52,
    price: 75000,
    cert: "Micro-certification Production e-learning",
    priority: "Vague 1",
  },
  {
    code: "PRG-EDU-03",
    school: "S09",
    title: "Administration et exploitation Moodle",
    slug: "administration-et-exploitation-moodle",
    courses: ["EDU-005", "EDU-017", "CYB-010"],
    volume: 60,
    price: 75000,
    cert: "Micro-certification Administration LMS",
    priority: "Vague 1",
  },
  {
    code: "PRG-EDU-04",
    school: "S09",
    title: "Création de cours Moodle",
    slug: "creation-de-cours-moodle",
    courses: ["EDU-006", "EDU-007", "EDU-008"],
    volume: 52,
    price: 75000,
    cert: "Micro-certification Création de cours Moodle",
    priority: "Vague 1",
  },
  {
    code: "PRG-EDU-05",
    school: "S09",
    title: "Animation et tutorat en ligne",
    slug: "animation-et-tutorat-en-ligne",
    courses: ["EDU-009", "EDU-011", "CORE-002"],
    volume: 40,
    price: 55000,
    cert: "Micro-certification Tutorat en ligne",
    priority: "Vague 1",
  },
  {
    code: "PRG-EDU-06",
    school: "S09",
    title: "Évaluation et certification des compétences",
    slug: "evaluation-et-certification-des-competences",
    courses: ["EDU-003", "EDU-007", "EDU-015"],
    volume: 48,
    price: 55000,
    cert: "Micro-certification Évaluation et certification",
    priority: "Vague 1",
  },
  {
    code: "PRG-EDU-07",
    school: "S09",
    title: "Learning Analytics et pilotage",
    slug: "learning-analytics-et-pilotage",
    courses: ["EDU-012", "DATA-019", "DATA-017"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification Learning Analytics",
    priority: "Vague 2",
  },
  {
    code: "PRG-EDU-08",
    school: "S09",
    title: "IA pour la conception pédagogique",
    slug: "ia-pour-la-conception-pedagogique",
    courses: ["EDU-014", "AI-003", "AI-007"],
    volume: 44,
    price: 55000,
    cert: "Micro-certification IA pédagogique",
    priority: "Vague 1",
  },
  {
    code: "PRG-EDU-09",
    school: "S09",
    title: "Qualité et accessibilité e-learning",
    slug: "qualite-et-accessibilite-e-learning",
    courses: ["EDU-013", "EDU-016", "CORE-006"],
    volume: 40,
    price: 55000,
    cert: "Micro-certification Qualité e-learning",
    priority: "Vague 1",
  },
];

// ---------------------------------------------------------------------------
// 46 Career Paths
// ---------------------------------------------------------------------------

const CAREER_PATHS: CareerPathData[] = [
  // ── PATH-AI (S01) — 4 paths ──────────────────────────────────────────
  {
    code: "PATH-AI-01",
    school: "S01",
    title: "Assistant IA professionnel",
    slug: "assistant-ia-professionnel",
    targetJob: "Assistant IA / collaborateur augmenté",
    duration: "3 mois",
    programs: ["PRG-AI-01", "PRG-AI-02", "PRG-AI-03", "PRG-AI-04", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Concevoir et documenter un assistant IA opérationnel pour une PME.",
    price: 135000,
    installments: "3 mensualités de 50 000 F CFA",
    cert: "Certificat Assistant IA professionnel",
    priority: "Vague 1",
  },
  {
    code: "PATH-AI-02",
    school: "S01",
    title: "Spécialiste en automatisation No-Code et IA",
    slug: "specialiste-en-automatisation-no-code-et-ia",
    targetJob: "Spécialiste automatisation junior",
    duration: "4 mois",
    programs: ["PRG-AI-01", "PRG-AI-02", "PRG-AI-05", "PRG-AI-06", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Automatiser un processus commercial ou administratif de bout en bout.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Spécialiste en automatisation numérique",
    priority: "Vague 2",
  },
  {
    code: "PATH-AI-03",
    school: "S01",
    title: "Concepteur d'agents IA junior",
    slug: "concepteur-dagents-ia-junior",
    targetJob: "Concepteur d'agents IA junior",
    duration: "5 mois",
    programs: ["PRG-AI-01", "PRG-AI-02", "PRG-AI-04", "PRG-AI-07", "PRG-DEV-06", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Créer un agent spécialisé relié à une base de connaissances et à des outils contrôlés.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Concepteur d'agents IA junior",
    priority: "Vague 3",
  },
  {
    code: "PATH-AI-04",
    school: "S01",
    title: "Référent IA en entreprise",
    slug: "referent-ia-en-entreprise",
    targetJob: "Référent IA / adoption numérique",
    duration: "4 mois",
    programs: ["PRG-AI-01", "PRG-AI-03", "PRG-AI-08", "PRG-CYB-09", "PRG-ENT-09", "PRG-CORE-02"],
    finalProject: "Élaborer un diagnostic, une politique d'usage et une feuille de route IA.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Référent IA et transformation des usages",
    priority: "Vague 2",
  },

  // ── PATH-DEV (S02) — 6 paths ─────────────────────────────────────────
  {
    code: "PATH-DEV-01",
    school: "S02",
    title: "Intégrateur Web professionnel",
    slug: "integrateur-web-professionnel",
    targetJob: "Intégrateur Web",
    duration: "3 mois",
    programs: ["PRG-DEV-01", "PRG-DEV-03", "PRG-DEV-09", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Créer et déployer le site institutionnel responsive d'une organisation.",
    price: 135000,
    installments: "3 mensualités de 50 000 F CFA",
    cert: "Certificat Intégrateur Web professionnel",
    priority: "Vague 2",
  },
  {
    code: "PATH-DEV-02",
    school: "S02",
    title: "Développeur Web Front-End",
    slug: "developpeur-web-front-end",
    targetJob: "Développeur Front-End junior",
    duration: "5 mois",
    programs: ["PRG-DEV-01", "PRG-DEV-02", "PRG-DEV-03", "PRG-DEV-04", "PRG-DEV-05", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Développer l'interface complète d'une plateforme Web responsive et accessible.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Développeur Front-End junior",
    priority: "Vague 1",
  },
  {
    code: "PATH-DEV-03",
    school: "S02",
    title: "Développeur Web Back-End",
    slug: "developpeur-web-back-end",
    targetJob: "Développeur Back-End junior",
    duration: "6 mois",
    programs: ["PRG-DEV-02", "PRG-DEV-03", "PRG-DEV-06", "PRG-DEV-07", "PRG-DEV-09", "PRG-CYB-06", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Concevoir une API sécurisée avec base de données, tests et documentation.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Développeur Back-End junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-DEV-04",
    school: "S02",
    title: "Développeur Full Stack",
    slug: "developpeur-full-stack",
    targetJob: "Développeur Full Stack junior",
    duration: "8 mois",
    programs: ["PRG-DEV-01", "PRG-DEV-02", "PRG-DEV-03", "PRG-DEV-04", "PRG-DEV-05", "PRG-DEV-06", "PRG-DEV-07", "PRG-DEV-09", "PRG-CYB-06", "PRG-ENT-07", "PRG-CORE-04"],
    finalProject: "Développer, tester, sécuriser et déployer une plateforme SaaS complète.",
    price: 360000,
    installments: "8 mensualités de 50 000 F CFA",
    cert: "Certificat Développeur Full Stack junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-DEV-05",
    school: "S02",
    title: "Développeur mobile multiplateforme",
    slug: "developpeur-mobile-multiplateforme-path",
    targetJob: "Développeur mobile junior",
    duration: "6 mois",
    programs: ["PRG-DEV-02", "PRG-DEV-03", "PRG-DEV-07", "PRG-DEV-12", "PRG-DEV-09", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Créer une application mobile de services reliée à une API.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Développeur mobile junior",
    priority: "Vague 3",
  },
  {
    code: "PATH-DEV-06",
    school: "S02",
    title: "Concepteur d'applications No-Code",
    slug: "concepteur-dapplications-no-code",
    targetJob: "Concepteur No-Code junior",
    duration: "4 mois",
    programs: ["PRG-DEV-11", "PRG-AI-05", "PRG-DATA-01", "PRG-ENT-07", "PRG-CORE-04"],
    finalProject: "Créer une application métier No-Code avec données, workflow et interface.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Concepteur d'applications No-Code",
    priority: "Vague 2",
  },

  // ── PATH-DATA (S03) — 5 paths ────────────────────────────────────────
  {
    code: "PATH-DATA-01",
    school: "S03",
    title: "Gestionnaire de données junior",
    slug: "gestionnaire-de-donnees-junior",
    targetJob: "Gestionnaire de données junior",
    duration: "3 mois",
    programs: ["PRG-DATA-01", "PRG-DATA-02", "PRG-DATA-04", "PRG-PROD-07", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Nettoyer, structurer et documenter une base de données opérationnelle.",
    price: 135000,
    installments: "3 mensualités de 50 000 F CFA",
    cert: "Certificat Gestionnaire de données junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-DATA-02",
    school: "S03",
    title: "Analyste de données junior",
    slug: "analyste-de-donnees-junior",
    targetJob: "Analyste de données junior",
    duration: "5 mois",
    programs: ["PRG-DATA-01", "PRG-DATA-02", "PRG-DATA-03", "PRG-DATA-04", "PRG-DATA-06", "PRG-DATA-10", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Réaliser une analyse complète et présenter des recommandations décisionnelles.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Analyste de données junior",
    priority: "Vague 1",
  },
  {
    code: "PATH-DATA-03",
    school: "S03",
    title: "Concepteur de tableaux de bord",
    slug: "concepteur-de-tableaux-de-bord",
    targetJob: "Concepteur de tableaux de bord",
    duration: "4 mois",
    programs: ["PRG-DATA-02", "PRG-DATA-03", "PRG-DATA-06", "PRG-DATA-07", "PRG-DATA-09", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Créer un tableau de bord de pilotage complet pour une PME.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Concepteur de tableaux de bord",
    priority: "Vague 2",
  },
  {
    code: "PATH-DATA-04",
    school: "S03",
    title: "Gestionnaire de bases de données junior",
    slug: "gestionnaire-de-bases-de-donnees-junior",
    targetJob: "Gestionnaire de bases de données junior",
    duration: "5 mois",
    programs: ["PRG-DATA-01", "PRG-DATA-04", "PRG-DATA-05", "PRG-CYB-04", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Concevoir, sécuriser, sauvegarder et administrer une base relationnelle.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Gestionnaire de bases de données junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-DATA-05",
    school: "S03",
    title: "Analyste en Intelligence décisionnelle",
    slug: "analyste-en-intelligence-decisionnelle",
    targetJob: "Analyste BI junior",
    duration: "6 mois",
    programs: ["PRG-DATA-01", "PRG-DATA-04", "PRG-DATA-06", "PRG-DATA-07", "PRG-DATA-09", "PRG-DATA-10", "PRG-ENT-09", "PRG-CORE-04"],
    finalProject: "Construire une solution de Business Intelligence avec modèle, indicateurs et rapport.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Analyste BI junior",
    priority: "Vague 3",
  },

  // ── PATH-CYB (S04) — 5 paths ─────────────────────────────────────────
  {
    code: "PATH-CYB-01",
    school: "S04",
    title: "Technicien support informatique",
    slug: "technicien-support-informatique",
    targetJob: "Technicien support informatique",
    duration: "4 mois",
    programs: ["PRG-CYB-01", "PRG-CYB-02", "PRG-CYB-03", "PRG-CYB-04", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Mettre en place un service de support, de suivi des tickets et de maintenance.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Technicien support informatique",
    priority: "Vague 1",
  },
  {
    code: "PATH-CYB-02",
    school: "S04",
    title: "Administrateur systèmes et réseaux junior",
    slug: "administrateur-systemes-et-reseaux-junior",
    targetJob: "Administrateur systèmes et réseaux junior",
    duration: "6 mois",
    programs: ["PRG-CYB-01", "PRG-CYB-02", "PRG-CYB-03", "PRG-CYB-04", "PRG-DEV-09", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Déployer une petite infrastructure sécurisée, documentée et sauvegardée.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Administrateur systèmes et réseaux junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-CYB-03",
    school: "S04",
    title: "Technicien en cybersécurité",
    slug: "technicien-en-cybersecurite",
    targetJob: "Technicien cybersécurité junior",
    duration: "5 mois",
    programs: ["PRG-CYB-02", "PRG-CYB-03", "PRG-CYB-04", "PRG-CYB-06", "PRG-CYB-08", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Réaliser un diagnostic de sécurité et un plan de correction pour une PME.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Technicien en cybersécurité",
    priority: "Vague 2",
  },
  {
    code: "PATH-CYB-04",
    school: "S04",
    title: "Analyste SOC junior",
    slug: "analyste-soc-junior",
    targetJob: "Analyste SOC junior",
    duration: "6 mois",
    programs: ["PRG-CYB-02", "PRG-CYB-03", "PRG-CYB-06", "PRG-CYB-07", "PRG-CYB-09", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Analyser et documenter un scénario d'incident à partir de journaux.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Analyste SOC junior",
    priority: "Vague 3",
  },
  {
    code: "PATH-CYB-05",
    school: "S04",
    title: "Référent sécurité numérique pour PME",
    slug: "referent-securite-numerique-pour-pme",
    targetJob: "Référent sécurité numérique",
    duration: "4 mois",
    programs: ["PRG-CYB-03", "PRG-CYB-04", "PRG-CYB-08", "PRG-CYB-09", "PRG-ENT-09", "PRG-CORE-02"],
    finalProject: "Élaborer la politique et le plan de sécurité numérique d'une organisation.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Référent sécurité numérique",
    priority: "Vague 2",
  },

  // ── PATH-MKT (S05) — 6 paths ─────────────────────────────────────────
  {
    code: "PATH-MKT-01",
    school: "S05",
    title: "Community Manager professionnel",
    slug: "community-manager-professionnel",
    targetJob: "Community Manager",
    duration: "4 mois",
    programs: ["PRG-MKT-01", "PRG-MKT-02", "PRG-MKT-03", "PRG-MKT-04", "PRG-MKT-11", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Construire et exécuter une stratégie social media complète pour une PME.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Community Manager professionnel",
    priority: "Vague 1",
  },
  {
    code: "PATH-MKT-02",
    school: "S05",
    title: "Créateur de contenu digital",
    slug: "createur-de-contenu-digital",
    targetJob: "Créateur de contenu digital",
    duration: "4 mois",
    programs: ["PRG-MKT-01", "PRG-MKT-03", "PRG-DES-06", "PRG-DES-09", "PRG-AI-09", "PRG-CORE-04"],
    finalProject: "Produire une campagne multiformat cohérente et documentée.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Créateur de contenu digital",
    priority: "Vague 2",
  },
  {
    code: "PATH-MKT-03",
    school: "S05",
    title: "Spécialiste en acquisition digitale",
    slug: "specialiste-en-acquisition-digitale",
    targetJob: "Spécialiste acquisition junior",
    duration: "5 mois",
    programs: ["PRG-MKT-01", "PRG-MKT-04", "PRG-MKT-05", "PRG-MKT-06", "PRG-MKT-07", "PRG-MKT-11", "PRG-DATA-09", "PRG-CORE-04"],
    finalProject: "Concevoir, budgéter et mesurer une campagne d'acquisition multicanale.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Spécialiste en acquisition digitale",
    priority: "Vague 3",
  },
  {
    code: "PATH-MKT-04",
    school: "S05",
    title: "Responsable de boutique en ligne",
    slug: "responsable-de-boutique-en-ligne",
    targetJob: "Responsable e-commerce junior",
    duration: "5 mois",
    programs: ["PRG-MKT-01", "PRG-MKT-08", "PRG-MKT-09", "PRG-MKT-10", "PRG-DATA-03", "PRG-ENT-06", "PRG-CORE-04"],
    finalProject: "Créer, lancer et piloter une boutique en ligne complète.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Responsable e-commerce junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-MKT-05",
    school: "S05",
    title: "Commercial digital et gestionnaire CRM",
    slug: "commercial-digital-et-gestionnaire-crm",
    targetJob: "Commercial digital / gestionnaire CRM",
    duration: "4 mois",
    programs: ["PRG-MKT-01", "PRG-MKT-08", "PRG-MKT-07", "PRG-ENT-04", "PRG-ENT-05", "PRG-CORE-04"],
    finalProject: "Mettre en place un processus de prospection et de suivi des ventes.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Commercial digital",
    priority: "Vague 2",
  },
  {
    code: "PATH-MKT-06",
    school: "S05",
    title: "Référenceur SEO junior",
    slug: "referenceur-seo-junior",
    targetJob: "Référenceur SEO junior",
    duration: "4 mois",
    programs: ["PRG-MKT-01", "PRG-MKT-06", "PRG-DATA-09", "PRG-DEV-10", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Réaliser l'audit et l'optimisation éditoriale et technique d'un site.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Référenceur SEO junior",
    priority: "Vague 2",
  },

  // ── PATH-DES (S06) — 5 paths ─────────────────────────────────────────
  {
    code: "PATH-DES-01",
    school: "S06",
    title: "Graphiste Digital",
    slug: "graphiste-digital",
    targetJob: "Graphiste Digital junior",
    duration: "4 mois",
    programs: ["PRG-DES-01", "PRG-DES-02", "PRG-DES-03", "PRG-DES-04", "PRG-DES-09", "PRG-CORE-04"],
    finalProject: "Créer l'identité visuelle complète d'une marque et ses supports.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Graphiste Digital",
    priority: "Vague 1",
  },
  {
    code: "PATH-DES-02",
    school: "S06",
    title: "Designer UX/UI",
    slug: "designer-ux-ui",
    targetJob: "Designer UX/UI junior",
    duration: "6 mois",
    programs: ["PRG-DES-01", "PRG-DES-05", "PRG-DES-09", "PRG-DEV-01", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Concevoir, prototyper et tester une application Web ou mobile.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Designer UX/UI junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-DES-03",
    school: "S06",
    title: "Monteur vidéo professionnel",
    slug: "monteur-video-professionnel-path",
    targetJob: "Monteur vidéo",
    duration: "4 mois",
    programs: ["PRG-DES-06", "PRG-DES-07", "PRG-DES-09", "PRG-MKT-03", "PRG-CORE-04"],
    finalProject: "Produire une vidéo promotionnelle complète pour une organisation.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Monteur vidéo professionnel",
    priority: "Vague 2",
  },
  {
    code: "PATH-DES-04",
    school: "S06",
    title: "Motion Designer junior",
    slug: "motion-designer-junior-path",
    targetJob: "Motion Designer junior",
    duration: "6 mois",
    programs: ["PRG-DES-01", "PRG-DES-07", "PRG-DES-08", "PRG-DES-09", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Créer une campagne animée et son système graphique.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Motion Designer junior",
    priority: "Vague 3",
  },
  {
    code: "PATH-DES-05",
    school: "S06",
    title: "Créateur de contenus visuels pour les réseaux sociaux",
    slug: "createur-de-contenus-visuels-pour-les-reseaux-sociaux",
    targetJob: "Créateur de contenus visuels",
    duration: "3 mois",
    programs: ["PRG-DES-01", "PRG-DES-02", "PRG-DES-06", "PRG-MKT-03", "PRG-CORE-04"],
    finalProject: "Produire un kit mensuel de contenus visuels et vidéo pour une entreprise.",
    price: 135000,
    installments: "3 mensualités de 50 000 F CFA",
    cert: "Certificat Créateur de contenus visuels",
    priority: "Vague 2",
  },

  // ── PATH-PROD (S07) — 5 paths ────────────────────────────────────────
  {
    code: "PATH-PROD-01",
    school: "S07",
    title: "Assistant administratif numérique",
    slug: "assistant-administratif-numerique",
    targetJob: "Assistant administratif numérique",
    duration: "4 mois",
    programs: ["PRG-PROD-01", "PRG-PROD-03", "PRG-PROD-04", "PRG-PROD-05", "PRG-PROD-06", "PRG-PROD-09", "PRG-CORE-04"],
    finalProject: "Digitaliser l'organisation, les documents, réunions et suivis d'un secrétariat.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Assistant administratif numérique",
    priority: "Vague 1",
  },
  {
    code: "PATH-PROD-02",
    school: "S07",
    title: "Assistant virtuel professionnel",
    slug: "assistant-virtuel-professionnel",
    targetJob: "Assistant virtuel",
    duration: "4 mois",
    programs: ["PRG-PROD-03", "PRG-PROD-05", "PRG-PROD-08", "PRG-PROD-09", "PRG-ENT-05", "PRG-CORE-05", "PRG-CORE-04"],
    finalProject: "Créer et gérer une offre d'assistance à distance pour plusieurs clients.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Assistant virtuel professionnel",
    priority: "Vague 2",
  },
  {
    code: "PATH-PROD-03",
    school: "S07",
    title: "Gestionnaire documentaire numérique",
    slug: "gestionnaire-documentaire-numerique",
    targetJob: "Gestionnaire documentaire numérique",
    duration: "4 mois",
    programs: ["PRG-PROD-02", "PRG-PROD-03", "PRG-PROD-04", "PRG-PROD-07", "PRG-CYB-04", "PRG-CORE-04"],
    finalProject: "Concevoir un système complet de classement, partage, archivage et collecte.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Gestionnaire documentaire numérique",
    priority: "Vague 2",
  },
  {
    code: "PATH-PROD-04",
    school: "S07",
    title: "Spécialiste bureautique et reporting",
    slug: "specialiste-bureautique-et-reporting",
    targetJob: "Spécialiste bureautique et reporting",
    duration: "4 mois",
    programs: ["PRG-PROD-01", "PRG-PROD-02", "PRG-PROD-06", "PRG-DATA-03", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Produire un dispositif de documents, tableaux et présentations de reporting.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Spécialiste bureautique et reporting",
    priority: "Vague 2",
  },
  {
    code: "PATH-PROD-05",
    school: "S07",
    title: "Coordinateur administratif numérique",
    slug: "coordinateur-administratif-numerique",
    targetJob: "Coordinateur administratif numérique",
    duration: "5 mois",
    programs: ["PRG-PROD-02", "PRG-PROD-03", "PRG-PROD-04", "PRG-PROD-05", "PRG-PROD-06", "PRG-PROD-08", "PRG-ENT-07", "PRG-CORE-04"],
    finalProject: "Organiser et piloter les processus administratifs numériques d'une structure.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Coordinateur administratif numérique",
    priority: "Vague 3",
  },

  // ── PATH-ENT (S08) — 5 paths ─────────────────────────────────────────
  {
    code: "PATH-ENT-01",
    school: "S08",
    title: "Freelance numérique professionnel",
    slug: "freelance-numerique-professionnel",
    targetJob: "Freelance numérique",
    duration: "3 mois",
    programs: ["PRG-ENT-01", "PRG-ENT-03", "PRG-ENT-04", "PRG-ENT-05", "PRG-ENT-06", "PRG-CORE-04"],
    finalProject: "Construire, présenter et commercialiser une offre de service complète.",
    price: 135000,
    installments: "3 mensualités de 50 000 F CFA",
    cert: "Certificat Freelance numérique professionnel",
    priority: "Vague 1",
  },
  {
    code: "PATH-ENT-02",
    school: "S08",
    title: "Entrepreneur Digital",
    slug: "entrepreneur-digital",
    targetJob: "Entrepreneur Digital",
    duration: "5 mois",
    programs: ["PRG-ENT-01", "PRG-ENT-02", "PRG-ENT-03", "PRG-ENT-04", "PRG-ENT-06", "PRG-ENT-08", "PRG-MKT-01", "PRG-CORE-04"],
    finalProject: "Lancer un produit ou service numérique et suivre ses premiers résultats.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Entrepreneur Digital",
    priority: "Vague 2",
  },
  {
    code: "PATH-ENT-03",
    school: "S08",
    title: "Chef de projet digital junior",
    slug: "chef-de-projet-digital-junior",
    targetJob: "Chef de projet digital junior",
    duration: "5 mois",
    programs: ["PRG-ENT-07", "PRG-ENT-08", "PRG-CORE-02", "PRG-CORE-03", "PRG-DATA-09", "PRG-CORE-04"],
    finalProject: "Piloter un projet numérique de la définition à la livraison.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Chef de projet digital junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-ENT-04",
    school: "S08",
    title: "Consultant en transformation numérique junior",
    slug: "consultant-en-transformation-numerique-junior",
    targetJob: "Consultant numérique junior",
    duration: "6 mois",
    programs: ["PRG-ENT-09", "PRG-AI-08", "PRG-DATA-09", "PRG-CYB-08", "PRG-PROD-09", "PRG-ENT-05", "PRG-CORE-04"],
    finalProject: "Élaborer un diagnostic et un plan de transformation réaliste pour une PME.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Consultant en transformation numérique junior",
    priority: "Vague 3",
  },
  {
    code: "PATH-ENT-05",
    school: "S08",
    title: "Responsable des opérations numériques pour PME",
    slug: "responsable-des-operations-numeriques-pour-pme",
    targetJob: "Responsable opérations numériques junior",
    duration: "5 mois",
    programs: ["PRG-ENT-09", "PRG-PROD-06", "PRG-PROD-07", "PRG-MKT-08", "PRG-AI-05", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Digitaliser et documenter plusieurs processus clés d'une PME.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Responsable des opérations numériques",
    priority: "Vague 3",
  },

  // ── PATH-EDU (S09) — 5 paths ─────────────────────────────────────────
  {
    code: "PATH-EDU-01",
    school: "S09",
    title: "Concepteur pédagogique numérique",
    slug: "concepteur-pedagogique-numerique",
    targetJob: "Concepteur pédagogique numérique",
    duration: "5 mois",
    programs: ["PRG-EDU-01", "PRG-EDU-02", "PRG-EDU-04", "PRG-EDU-06", "PRG-EDU-08", "PRG-EDU-09", "PRG-CORE-03", "PRG-CORE-04"],
    finalProject: "Concevoir un parcours complet avec activités, évaluations et preuves de compétences.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Concepteur pédagogique numérique",
    priority: "Vague 1",
  },
  {
    code: "PATH-EDU-02",
    school: "S09",
    title: "Administrateur de plateforme LMS",
    slug: "administrateur-de-plateforme-lms",
    targetJob: "Administrateur LMS junior",
    duration: "5 mois",
    programs: ["PRG-EDU-03", "PRG-EDU-04", "PRG-EDU-07", "PRG-CYB-04", "PRG-CORE-02", "PRG-CORE-04"],
    finalProject: "Déployer, configurer et administrer une plateforme de formation.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Administrateur LMS junior",
    priority: "Vague 2",
  },
  {
    code: "PATH-EDU-03",
    school: "S09",
    title: "Formateur en ligne professionnel",
    slug: "formateur-en-ligne-professionnel",
    targetJob: "Formateur en ligne",
    duration: "4 mois",
    programs: ["PRG-EDU-01", "PRG-EDU-02", "PRG-EDU-05", "PRG-EDU-06", "PRG-EDU-08", "PRG-CORE-04"],
    finalProject: "Concevoir et animer une formation en ligne complète.",
    price: 180000,
    installments: "4 mensualités de 50 000 F CFA",
    cert: "Certificat Formateur en ligne professionnel",
    priority: "Vague 2",
  },
  {
    code: "PATH-EDU-04",
    school: "S09",
    title: "Producteur de contenus e-learning",
    slug: "producteur-de-contenus-e-learning",
    targetJob: "Producteur de contenus e-learning",
    duration: "5 mois",
    programs: ["PRG-EDU-01", "PRG-EDU-02", "PRG-EDU-04", "PRG-DES-07", "PRG-AI-09", "PRG-EDU-09", "PRG-CORE-04"],
    finalProject: "Produire un module multimédia interactif et accessible.",
    price: 225000,
    installments: "5 mensualités de 50 000 F CFA",
    cert: "Certificat Producteur de contenus e-learning",
    priority: "Vague 2",
  },
  {
    code: "PATH-EDU-05",
    school: "S09",
    title: "Responsable de formation digitale junior",
    slug: "responsable-de-formation-digitale-junior",
    targetJob: "Responsable formation digitale junior",
    duration: "6 mois",
    programs: ["PRG-EDU-01", "PRG-EDU-03", "PRG-EDU-05", "PRG-EDU-06", "PRG-EDU-07", "PRG-EDU-09", "PRG-ENT-07", "PRG-CORE-04"],
    finalProject: "Élaborer et piloter un dispositif de formation numérique avec indicateurs qualité.",
    price: 270000,
    installments: "6 mensualités de 50 000 F CFA",
    cert: "Certificat Responsable de formation digitale junior",
    priority: "Vague 3",
  },
];

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
  console.log("=== catalogue-seed-part2: Programs & Career Paths ===\n");

  // 1. Load courses into a map: code → id
  const courses = await prisma.course.findMany({
    where: { code: { not: null } },
    select: { id: true, code: true },
  });
  const courseMap: Record<string, string> = {};
  for (const c of courses) {
    if (c.code) courseMap[c.code] = c.id;
  }
  console.log(`Loaded ${Object.keys(courseMap).length} courses from DB.`);

  // 2. Load schools into a map: code → id
  const schools = await prisma.school.findMany({
    where: { code: { not: null } },
    select: { id: true, code: true },
  });
  const schoolMap: Record<string, string> = {};
  for (const s of schools) {
    if (s.code) schoolMap[s.code] = s.id;
  }
  console.log(`Loaded ${Object.keys(schoolMap).length} schools from DB.\n`);

  // 3. Upsert all 92 programs
  const programMap: Record<string, string> = {};
  let programCount = 0;
  let programCourseCount = 0;

  for (const p of PROGRAMS) {
    const schoolId = schoolMap[p.school];
    if (!schoolId) {
      console.warn(`  [WARN] Missing school ${p.school} for program ${p.code} — skipping.`);
      continue;
    }

    const program = await prisma.program.upsert({
      where: { slug: p.slug },
      update: {
        code: p.code,
        title: p.title,
        volume: p.volume,
        price: p.price,
        certificationTitle: p.cert,
        priority: p.priority,
        schoolId,
      },
      create: {
        code: p.code,
        title: p.title,
        slug: p.slug,
        volume: p.volume,
        price: p.price,
        certificationTitle: p.cert,
        priority: p.priority,
        status: "DRAFT",
        schoolId,
      },
    });

    programMap[p.code] = program.id;
    programCount++;

    // Link courses via ProgramCourse junction
    for (let i = 0; i < p.courses.length; i++) {
      const courseId = courseMap[p.courses[i]];
      if (!courseId) {
        console.warn(`  [WARN] Missing course ${p.courses[i]} for program ${p.code}`);
        continue;
      }
      await prisma.programCourse.upsert({
        where: { programId_courseId: { programId: program.id, courseId } },
        update: { position: i },
        create: { programId: program.id, courseId, position: i },
      });
      programCourseCount++;
    }

    if (programCount % 20 === 0) {
      console.log(`  ... ${programCount} programs upserted`);
    }
  }

  console.log(`\nPrograms: ${programCount} upserted, ${programCourseCount} program-course links.\n`);

  // 4. Upsert all 46 career paths
  let pathCount = 0;
  let pathProgramCount = 0;
  let schoolPathCount = 0;

  for (let idx = 0; idx < CAREER_PATHS.length; idx++) {
    const cp = CAREER_PATHS[idx];
    const schoolId = schoolMap[cp.school];

    const path = await prisma.careerPath.upsert({
      where: { slug: cp.slug },
      update: {
        code: cp.code,
        title: cp.title,
        targetJob: cp.targetJob,
        description: cp.finalProject,
        duration: cp.duration,
        price: cp.price,
        installments: cp.installments,
        certificationTitle: cp.cert,
        priority: cp.priority,
      },
      create: {
        code: cp.code,
        title: cp.title,
        slug: cp.slug,
        targetJob: cp.targetJob,
        description: cp.finalProject,
        duration: cp.duration,
        price: cp.price,
        installments: cp.installments,
        certificationTitle: cp.cert,
        priority: cp.priority,
        status: "DRAFT",
      },
    });

    pathCount++;

    // Link to school via SchoolCareerPath
    if (schoolId) {
      await prisma.schoolCareerPath.upsert({
        where: { schoolId_careerPathId: { schoolId, careerPathId: path.id } },
        update: {},
        create: { schoolId, careerPathId: path.id, isPrimary: true, position: idx },
      });
      schoolPathCount++;
    } else {
      console.warn(`  [WARN] Missing school ${cp.school} for path ${cp.code}`);
    }

    // Link programs via CareerPathProgram
    for (let i = 0; i < cp.programs.length; i++) {
      const programId = programMap[cp.programs[i]];
      if (!programId) {
        console.warn(`  [WARN] Missing program ${cp.programs[i]} for path ${cp.code}`);
        continue;
      }
      await prisma.careerPathProgram.upsert({
        where: { careerPathId_programId: { careerPathId: path.id, programId } },
        update: { position: i },
        create: { careerPathId: path.id, programId, position: i, isRequired: true },
      });
      pathProgramCount++;
    }

    if (pathCount % 10 === 0) {
      console.log(`  ... ${pathCount} career paths upserted`);
    }
  }

  console.log(`\nCareer Paths: ${pathCount} upserted, ${pathProgramCount} path-program links, ${schoolPathCount} school-path links.\n`);

  // Summary
  console.log("=== Summary ===");
  console.log(`  Programs:           ${programCount} / ${PROGRAMS.length}`);
  console.log(`  Program-Course:     ${programCourseCount} links`);
  console.log(`  Career Paths:       ${pathCount} / ${CAREER_PATHS.length}`);
  console.log(`  Path-Program:       ${pathProgramCount} links`);
  console.log(`  School-Path:        ${schoolPathCount} links`);
  console.log("=== Done ===");
}

main()
  .then(() => prisma.$disconnect())
  .catch((e) => {
    console.error(e);
    prisma.$disconnect();
    process.exit(1);
  });
